# Generated by Django 2.0.4 on 2018-05-01 14:49

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(blank=True, max_length=30)),
                ('bio', models.CharField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('skils', models.CharField(blank=True, max_length=30)),
                ('education', models.CharField(blank=True, max_length=30)),
                ('edu_center', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('linkedin_profile', models.URLField(blank=True)),
                ('twitter_profile', models.URLField(blank=True)),
                ('facebook_profile', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=accounts.models.get_upload_image_name)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
