# Generated by Django 2.0.4 on 2018-10-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromUserId', models.CharField(blank=True, max_length=30)),
                ('toUserId', models.CharField(blank=True, max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('requestDate', models.DateTimeField(auto_now_add=True)),
                ('conformDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
