# Generated by Django 2.0.4 on 2018-10-14 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_friendsdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendsData',
        ),
        migrations.AddField(
            model_name='friend',
            name='conformDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='friend',
            name='requestDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friend',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
